# frozen_string_literal: true

require 'rake/testtask'
require_relative 'calculator_cli_app/src/application'
require_relative 'fibonacci_sequence/src/application'
require_relative 'fizzbuzz/src/application'

task default: :test

desc 'Run CalculatorCliApp::Application'
Rake::Task.define_task(:run_calculator_cli_app) do
  CalculatorCliApp::Application.run!(ARGV)
end

desc 'Print fibonacci sequence'
Rake::Task.define_task(:print_fibonacci_sequence) do
  puts 'Provide the initial number to start the sequence from'
  init_num = $stdin.gets&.chomp&.strip

  puts 'Provide the number of iterations'
  iter = $stdin.gets&.chomp&.strip

  params = { init_num:, iter: }.reject { |_, value| value&.empty? }.map { |_, value| [_, value.to_i] }.to_h
  puts fibonacci(**params).join(', ')
end

desc 'Print fizzbuzz sequence'
Rake::Task.define_task(:print_fizzbuzz_sequence) do
  puts 'Provide the initial number to start the sequence from'
  init_num = $stdin.gets&.chomp&.strip

  puts 'Provide the terminal number of stop the sequence at'
  terminal_num = $stdin.gets&.chomp&.strip

  puts 'Which logic do you want to use? (1: if, 2: if and ternary, 3: ternary)'
  logic_type = $stdin.gets&.chomp&.strip

  params = ({ init_num:, terminal_num:, logic_type: }.reject { |_, value| value&.empty? }.map { |_, value| [_, value.to_i] }.to_h)
  init_num, terminal_num, logic_type = params.values_at(:init_num, :terminal_num, :logic_type)

  result = init_num.upto(terminal_num).map { |num|
    if logic_type == 1
      fizzbuzz_in_if(num)
    elsif logic_type == 2
      fizzbuzz_in_if_and_ternary(num)
    elsif logic_type == 3
      fizzbuzz_in_ternary(num)
    else
      num
    end
  }

  puts result.join(', ')
end

desc 'Run all tests'
Rake::TestTask.new do |task|
  task.pattern = File.join('.', '**', '*_test.rb')
end
