D = Steep::Diagnostic

target :app do
  check "calculator_cli_app"
  check "fibonacci_sequence"
  check "fizzbuzz"
  check "letter_inspection"
  check "nabeatsu"
  signature "sig"

  library "json"
  library "net-http"

  configure_code_diagnostics(D::Ruby.default)
end
