# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Jest

on:
  push:
    branches:
      - master
    paths:
      - ./javascript
      - '!./javascript/README.md'
  pull_request:
    branches:
      - master
    paths:
      - ./javascript
      - '!./javascript/README.md'

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./javascript/yarn.lock
      - name: Install Packages
        working-directory: ./javascript
        run: yarn install
      - name: Run Jest
        working-directory: ./javascript
        run: npx jest
